development:
  adapter: postgresql
  encoding: unicode
  database: docm_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: docm_test
  pool: 5
  host: localhost
  <% if ENV['TRAVIS_BUILD'] %>
  username: postgres
  <% end %>

production:
  adapter: postgresql
  encoding: unicode
  database: docm
  pool: 5
  host: localhost
